Accounts/urls.py
from django.conf.urls import url
from . import views

app_name = "accounts"

urlpatterns = [
    url('^login-usuario/$', views.user_login, name='user-login'),
    url('^logout-usuario/$', views.user_logout, name='user-logout'),
    url('^novo-usuario/$', views.add_user, name='add-user'),
    url('^alterar-senha/$', views.change_password, name='change-password'),
    url('^update-dados/$', views.update_dados, name='update-dados'),
    url('^lista-usuarios/$', views.lista_usuarios, name = 'lista-usuarios'),
    url('^delete-usuario/(?P<id>[0-9]+)/$', views.delete_usuario, name = 'delete-usuario'),
    url('^update-usuario/(?P<id>[0-9]+)/$', views.update_usuario, name = 'update-usuario'),
]

New_Meire/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views
from Mensagens import views as mensagens_views
from Accounts import urls as accounts_urls
from Mensagens import urls as mensagens_urls
from Servico import urls as servico_urls
from Promocao import urls as promocao_urls
from cabeleireira import urls as cabeleireira_urls
from Agendar_horario import urls as agenda_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'core'),
    path('404', views.error_404, name ='error-404'),
    path('em-andamento', views.em_andamento, name ='em-andamento'),
    path('gerencia', views.gerencia, name='gerencia'),
    path('contato/', mensagens_views.nova_mensagem, name = 'contato'),
    path('accounts/', include(accounts_urls)),
    path('msg/', include(mensagens_urls)),
    path('servico/', include(servico_urls)),
    path('promocoes/', include(promocao_urls)),
    path('cabeleireira/', include(cabeleireira_urls)),
    path('agenda/', include(agenda_urls)),
]

Servico/urls.py
from django.conf.urls import url

from . import views
app_name = "servico"
urlpatterns = [
    url('^all-services/$', views.lista_servico, name = 'lista-servicos'),
    url('^novo-servico/$', views.add_servico, name = 'novo-servico'),
    url('^editar-servico/(?P<id>[0-9]+)/$', views.update_servico, name = 'editar-servico'),
    url('^excluir-servico/(?P<id>[0-9]+)/$', views.delete_servico, name = 'excluir-servico'),
]

Accounts/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Usuario(models.Model):
    cpf = models.CharField(max_length=11, verbose_name= 'CPF', blank=False)
    rg = models.CharField(max_length=7, verbose_name='RG', blank=False)
    telefone = models.CharField(max_length=12,verbose_name='Telefone', blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.get_full_name()

Accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Usuario

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password')

class UsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        exclude = ('user',)

class UpdateUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        exclude = ('cpf', 'rg', 'user',)

class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class AdminUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuario
        fields = '__all__'

class AdminUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username')

Accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.http import HttpResponse
from .forms import UserForm, UsuarioForm, UpdateUsuarioForm, UpdateUserForm, AdminUsuarioForm, AdminUserForm
from .models import Usuario
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            login(request, user)
            return redirect(request.GET.get('next', '/'))
        else:
            messages.error(request, 'Usuario ou senha invalidos!')
    return render(request, 'accounts/login.html')

def user_logout(request):
    logout(request)
    return redirect('core')

def add_user(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        formUsuario = UsuarioForm(request.POST)
        if formUsuario.is_valid():
            if form.is_valid():
                u = form.save()
                u.set_password(u.password)
                u.save()
                u2 = formUsuario.save(commit=False)
                u2.user = u #User.objects.get(pk = u.id)
                u2.save()
                messages.success(request, 'Usuário criado com sucesso! Utilize o formulario abaixo para fazer login!')
                return redirect('accounts:user-login')
            else:
                messages.error(request, form.errors)
        else:
            messages.error(request, formUsuario.errors)
    else:
        form = UserForm()
        formUsuario = UsuarioForm()
    return render(request, 'accounts/add_user.html', {'form':form, 'form1':formUsuario})

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Senha alterada com sucesso!')
            return redirect('accounts:change-password')
        else:
            messages.error(request, 'Não foi possivel alterar sua senha, verifique os dados!')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {'form':form})

@login_required
def update_dados(request):
    for u in Usuario.objects.all():
        if u.user == request.user:
            usuario = u
    
    if request.method == 'POST':
        usuario_form = UpdateUsuarioForm(data=request.POST, instance=usuario)
        user_form = UpdateUserForm(data=request.POST, instance=request.user)

        if usuario_form.is_valid():
            if user_form.is_valid():

                usuario_form.save()
                user_form.save()
                return redirect('accounts:update-dados')
            else:
                messages.error(request, user_form.errors)
        else:
            messages.error(request, usuario_form.errors)
    else:
        usuario_form = UpdateUsuarioForm(instance=usuario)
        user_form = UpdateUserForm(instance=request.user)
        return render(request, 'accounts/update_dados.html', {'usuario_form':usuario_form, 'user_form':user_form, 'usuario':usuario})

@login_required
def lista_usuarios(request):
    if request.user.is_superuser:
        usuarios = Usuario.objects.all()
        return render(request, 'accounts/lista_usuarios.html', {'usuarios': usuarios})
    else:
        return redirect('error-404')

@login_required
def delete_usuario(request, id):
    if request.user.is_superuser:
        usuario = Usuario.objects.get(pk=id)
        u = usuario.user
        usuario.delete()
        u.delete()
        return redirect('accounts:lista-usuarios')
    else:
        return redirect('error-404')

@login_required
def update_usuario(request, id):
    if request.user.is_superuser:
        usuario = Usuario.objects.get(pk = id)
        user = User.objects.get(pk = usuario.user.pk)
        if request.method == 'POST':
            usuario_form = UsuarioForm(data=request.POST, instance=usuario)
            user_form = AdminUserForm(data=request.POST, instance=user)
            if usuario_form.is_valid():
                if user_form.is_valid():
                    usuario_form.save()
                    user_form.save()
                    return redirect('accounts:lista-usuarios')
                else:
                    messages.error(request, user_form.errors)
                    return redirect('accounts:lista-usuarios')
            else:
                messages.error(request, usuario_form.errors)
                return redirect('accounts:lista-usuarios')
        else:
            usuario_form = UsuarioForm(instance=usuario)
            user_form = AdminUserForm(instance=user)
            return render(request, 'accounts/update_usuario.html', {'usuario_form':usuario_form, 'user_form':user_form})
    else:
        return redirect('error-404')

Accounts/templates/accounts/add_user.html
{% extends "index.html" %} 
{% load widget_tweaks %} 
{% block Body %}
<div class="login-addUser">

        <form form class="form-signin" method="post">
            {% csrf_token %} 
            <h3 class="h3 mb-3 font-weight-normal">Cadastre-se</h3>
            {% if messages %}
            <div class="alert alert-danger" role="alert">
                {% for m in messages %} {{ m }} {% endfor %}
            </div>
            {% endif %}
            <div class="form-group">
                <label for="{{form1.rg.id_for_label}}" class="sr-only">RG</label>
                {{form1.rg|add_class:'form-control'|attr:"placeholder:RG"}}
            </div>
            <div class="form-group">
                <label for="{{form1.CPF.id_for_label}}" class="sr-only">CPF</label>
                {{form1.cpf|add_class:'form-control'|attr:"placeholder:CPF"}}
            </div>
            <div class="form-group">
                <label for="{{form1.telefone.id_for_label}}" class="sr-only">telefone</label>
                {{form1.telefone|add_class:'form-control'|attr:"placeholder:telefone"}}
            </div>
            <div class="form-group">
                <label for="{{form.first_name.id_for_label}}" class="sr-only">Nome</label>
                {{form.first_name|add_class:'form-control'|attr:"placeholder:Nome"}}
            </div>
            <div class="form-group">
                <label for="{{form.last_name.id_for_label}}" class="sr-only">Sobrenome</label>
                {{form.last_name|add_class:'form-control'|attr:"placeholder:Sobrenome"}}
            </div>
            <div class="form-group">
                <label for="{{form.email.id_for_label}}" class="sr-only">Email</label>
                {{form.email|add_class:'form-control'|attr:"placeholder:Email"}}
            </div>
            <div class="form-group">
                <label for="{{form.username.id_for_label}}" class="sr-only">Username</label>
                {{form.username|add_class:'form-control'|attr:"placeholder:Username"}}
            </div>
            <div class="form-group">
                <label for="{{form.password.id_for_label}}" class="sr-only">Password</label>
                {% render_field form.password class="form-control" type="password" placeholder="Senha" %}
            </div>
            <button type="submit" class="btn btn-primary">Salvar</button>
            <a class="btn btn-secondary" href="{% url 'accounts:user-login' %}">Voltar</a>
        </form>
    </div>
    <br/>
    <br/>
    {% endblock Body %}

Accounts/templates/accounts/change_password.html
{% extends "index.html" %} {% load widget_tweaks %} {% block Body %}
<div class="login-addUser">
    {% if user.is_authenticated %}
    <form class="form-signin" method="post">
        {% csrf_token %}
        <h3 class="h3 mb-3 font-weight-normal">Trocar Senha</h3>

        {% if messages %}
        <div class="alert alert-warning" role="alert">
            {% for m in messages %} {{ m }} {% endfor %}
        </div>
        {% endif %}

        <div class="form-group">
            <label for="{{ form.old_password.id_for_label }}">Senha antiga:</label>
            {% render_field form.old_password class="form-control" type="password" %}
        </div>
        <div class="form-group">
            <label for="{{ form.new_password1.id_for_label }}">Nova senha:</label>
            {% render_field form.new_password1 class="form-control" type="password" %}
        </div>
        <div class="form-group">
            <label for="{{ form.new_password2.id_for_label }}">Confirmar nova senha:</label>
            {% render_field form.new_password2 class="form-control" type="password" %}
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
    {% else %}
    <h3 class="h3 mb-3 font-weight-normal">Você precisa estar logado!.</h3>
    {% endif %}
</div>
<br/>
<br/>
<br/> {% endblock Body %}

Accounts/templates/accounts/lista_usuarios.html
{% extends "index.html" %}
{% block Body %}
{% if user.is_authenticated %} 
{% if user.is_superuser %}
        <h1>Lista de Usuarios</h1>
        {% if messages %}
            {% for m in messages %}
                <div class="alert alert-danger" role="alert">
                    {{m}}
                </div>
            {% endfor %}
        {% endif %}
        {% if usuarios %}

            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Email</th>
                        <th>Telefone</th>
                        <th>Usuario</th>
                        <th colspan="2">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for u in usuarios %}
                        <tr>
                            <td>{{u.id}}</td>
                            <td>{{u.user.get_full_name}}</td>
                            <td>{{u.user.email}}</td>
                            <td>{{u.telefone}}</td>
                            <td>{{u.user.username}}</td>
                            <td>
                                <a href="{% url 'accounts:update-usuario' u.id %}" class="btn btn-success">Editar</a>
                                <a href="{% url 'accounts:delete-usuario' u.id %}" class="btn btn-danger">Excluir</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-info">
                <p>Ainda não cadastrou nenhum usuario!</p>
            </div>
        {% endif %}
{% endif %}{% endif %}
{% endblock Body %}

Accounts/templates/accounts/login.html
{% extends "index.html" %} 
{% load widget_tweaks %} 
{% block Body %}
<div class="login-addUser">
    
    {% if not user.is_authenticated %}
    <form class="form-signin" method="post">
        {% csrf_token %}
        <h3 class="h3 mb-3 font-weight-normal">Login</h3>

        {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for m in messages %} {{ m }} {% endfor %}
        </div>
        {% endif %}


        <label for="username" class="sr-only">Usuario</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Usuario" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <a class="nav-link" href="{% url 'accounts:add-user' %}">Não tem cadastro?</a>
    </form>
    {% else %}
        <h3 class="h3 mb-3 font-weight-normal">Você ja esta logado, {{user.get_full_name|default:user.username}}.</h3>
    {% endif %}
</div>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
{% endblock Body %}

Accounts/templates/accounts/update_dados.html
{% extends "index.html" %} {% load widget_tweaks %} {% block Body %}
<div class="login-addUser">

    {% if user.is_authenticated %}
    <form class="form-signin" method="post">
        {% csrf_token %}
        <h3 class="h3 mb-3 font-weight-normal">Atualize seus dados</h3>

        {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for m in messages %} {{ m }} {% endfor %}
        </div>
        {% endif %}

        <p>Login: {{user.username}}</p>
        <p>Senha: *********</p>
        <p>CPF: {{usuario.cpf}}</p>
        <p>RG: {{usuario.rg}}</p>

        <div class="form-group">
            <label for="{{user_form.first_name.id_for_label}}">Nome:</label>
            {{user_form.first_name|add_class:'form-control'|attr:"placeholder:Nome"}}
        </div>
        <div class="form-group">
            <label for="{{user_form.last_name.id_for_label}}">Sobrenome:</label>
            {{user_form.last_name|add_class:'form-control'|attr:"placeholder:Sobrenome"}}
        </div>
        <div class="form-group">
            <label for="{{user_form.email.id_for_label}}">Email:</label>
            {{user_form.email|add_class:'form-control'|attr:"placeholder:Email"}}
        </div>
        <div class="form-group">
            <label for="{{usuario_form.email.id_for_label}}">Telefone:</label>
            {{usuario_form.telefone|add_class:'form-control'|attr:"placeholder:Telefone"}}
        </div>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Salvar</button>
    </form>
    {% else %}
    <h3 class="h3 mb-3 font-weight-normal">Você precisa estar logado!.</h3>

    {% endif %}
</div>
<br/>
<br/>
<br/>
<br/> {% endblock Body %}

Accounts/templates/accounts/update_usuario.html
{% extends "index.html" %}
{% load widget_tweaks %}
{% block Body %}
{% if user.is_authenticated %} 
{% if user.is_superuser %}
    {% if messages %}
        {% for m in messages %}
            <div class="alert alert-danger" role="alert">
                {{m}}
            </div>
        {% endfor %}
    {% endif %}
    <form class="form-signin" method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Atualizar dados do Usuario</h1>

        {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for m in messages %} {{ m }} {% endfor %}
        </div>
        {% endif %}

        <div class="form-group">
            <label for="{{user_form.username.id_for_label}}">Username:</label>
            {{user_form.username|add_class:'form-control'|attr:"placeholder:Username"}}
        </div>
        <div class="form-group">
            <label for="{{user_form.first_name.id_for_label}}">Nome:</label>
            {{user_form.first_name|add_class:'form-control'|attr:"placeholder:Nome"}}
        </div>
        <div class="form-group">
            <label for="{{user_form.last_name.id_for_label}}">Sobrenome:</label>
            {{user_form.last_name|add_class:'form-control'|attr:"placeholder:Sobrenome"}}
        </div>
        <div class="form-group">
            <label for="{{user_form.email.id_for_label}}">Email:</label>
            {{user_form.email|add_class:'form-control'|attr:"placeholder:email"}}
        </div>

        <div class="form-group">
            <label for="{{form.cpf.id_for_label}}">CPF:</label>
            {{usuario_form.cpf|add_class:'form-control'|attr:"placeholder:CPF"}}
        </div>
        <div class="form-group">
            <label for="{{form.rg.id_for_label}}">RG:</label>
            {{usuario_form.rg|add_class:'form-control'|attr:"placeholder:RG"}}
        </div>
        <div class="form-group">
            <label for="{{form.telefone.id_for_label}}">Telefone:</label>
            {{usuario_form.telefone|add_class:'form-control'|attr:"placeholder:Telefone"}}
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Salvar</button>
        <a class="btn btn-lg btn-danger btn-block" href="">Redefinir Senha</a>
    </form>
{% endif %}
{% else %}
    <h3 class="h3 mb-3 font-weight-normal">Você precisa estar logado!.</h3>
{% endif %}
{% endblock Body %}