Accounts/urls.py
from django.conf.urls import url
from . import views

app_name = "accounts"

urlpatterns = [
    url('^login-usuario/$', views.user_login, name='user-login'),
    url('^logout-usuario/$', views.user_logout, name='user-logout'),
    url('^novo-usuario/$', views.add_user, name='add-user'),
    url('^alterar-senha/$', views.change_password, name='change-password'),
    url('^update-dados/$', views.update_dados, name='update-dados'),
    url('^lista-usuarios/$', views.lista_usuarios, name = 'lista-usuarios'),
    url('^delete-usuario/(?P<id>[0-9]+)/$', views.delete_usuario, name = 'delete-usuario'),
    url('^update-usuario/(?P<id>[0-9]+)/$', views.update_usuario, name = 'update-usuario'),
]

Mensagens/urls.py
from django.conf.urls import url

from . import views
app_name = "msg"
urlpatterns = [
    url('^mensagens/$', views.lista_mensagens, name = 'lista-mensagens'),
    url('^delete-mensagem/(?P<id>[0-9]+)/$', views.delete_mensagem, name = 'delete-mensagem'),
]

New_Meire/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views
from Mensagens import views as mensagens_views
from Accounts import urls as accounts_urls
from Mensagens import urls as mensagens_urls
from Servico import urls as servico_urls
from Promocao import urls as promocao_urls
from cabeleireira import urls as cabeleireira_urls
from Agendar_horario import urls as agenda_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'core'),
    path('404', views.error_404, name ='error-404'),
    path('em-andamento', views.em_andamento, name ='em-andamento'),
    path('gerencia', views.gerencia, name='gerencia'),
    path('contato/', mensagens_views.nova_mensagem, name = 'contato'),
    path('accounts/', include(accounts_urls)),
    path('msg/', include(mensagens_urls)),
    path('servico/', include(servico_urls)),
    path('promocoes/', include(promocao_urls)),
    path('cabeleireira/', include(cabeleireira_urls)),
    path('agenda/', include(agenda_urls)),
]

Promocao/urls.py
from django.conf.urls import url

from . import views
app_name = "promoções"
urlpatterns = [
    url('lista/', views.lista_promocoes, name = 'lista-promocoes'),
    url('nova/', views.add_promocao, name = 'nova-promocao'),
    url('editar/(?P<id>[0-9]+)/$', views.update_promocao, name = 'editar-promocao'),
    url('excluir/(?P<id>[0-9]+)/$', views.delete_promocao, name = 'excluir-promocao'),
]

Servico/urls.py
from django.conf.urls import url

from . import views
app_name = "servico"
urlpatterns = [
    url('^all-services/$', views.lista_servico, name = 'lista-servicos'),
    url('^novo-servico/$', views.add_servico, name = 'novo-servico'),
    url('^editar-servico/(?P<id>[0-9]+)/$', views.update_servico, name = 'editar-servico'),
    url('^excluir-servico/(?P<id>[0-9]+)/$', views.delete_servico, name = 'excluir-servico'),
]

cabeleireira/urls.py
from django.conf.urls import url

from . import views
app_name = "cabeleireira"
urlpatterns = [
    url('^lista-cabeleireira/$', views.lista_cabeleireira, name = 'lista-cabeleireira'),
    url('^nova-cabeleireira/$', views.add_cabeleireira, name = 'nova-cabeleireira'),
    url('^editar-cabeleireira/(?P<id>[0-9]+)/$', views.update_cabeleireira, name = 'editar-cabeleireira'),
    url('^excluir-cabeleireira/(?P<id>[0-9]+)/$', views.delete_cabeleireira, name = 'excluir-cabeleireira'),
    url('^novo-servico-cabeleireira/$', views.add_servicos_cabeleireira, name = 'novo-servico-cabeleireira'),
    url('^lista-servico-cabeleireira/(?P<id>[0-9]+)/$', views.lista_servicos_cabeleireira, name = 'lista-servico-cabeleireira'),
    url('^editar-servico-cabeleireira/(?P<id>[0-9]+)/$', views.update_servico_cabeleireira, name = 'editar-servico-cabeleireira'),
    url('^excluir-servico-cabeleireira/(?P<id>[0-9]+)/$', views.delete_servico_cabeleireira, name = 'excluir-servico-cabeleireira'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'core/home.html') #  Função usada para exibir o home

def error_404(request):
    return render(request, 'core/404.html')

def em_andamento(request):
    return render(request, 'core/em_andamento.html')

def gerencia(request):
    return render (request, 'core/gerencia.html')

core/templates/core/em_andamento.html
{% extends "index.html" %}

{% block Body %}
    <div class="row">
        <h1>Esta pagina ainda não foi criada! "Ainda" rsrs.</h1>
    </div>
{% endblock %}

core/templates/core/gerencia.html
{% extends "index.html" %}
{% block Body %}
{% if user.is_authenticated %}
{% if user.is_superuser %}
<h1>Tabela administrativa</h1>
<table class="table">
    <thead>
        <tr>
            <th>Usuarios</th>
            <th>Serviços</th>
            <th>Promoções</th>
            <th>Horarios</th>
            <th>Cabeleireiras</th>
            <th>Contato</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <a href="{% url 'accounts:lista-usuarios'%}" class="btn btn-success">Lista de Users</a>
            </td>
            <td>
                <a href="{% url 'servico:lista-servicos'%}" class="btn btn-success">Lista de Services</a>
            </td>
            <td>
                <a href="{% url 'promoções:lista-promocoes'%}" class="btn btn-success">Lista de Promoções</a>
            </td>
            <td>Ainda não</td>
            <td>
                <a href="{% url 'cabeleireira:lista-cabeleireira'%}" class="btn btn-success">Lista de Cabeleireiras</a>
            </td>
            <td>
                <a href="{% url 'msg:lista-mensagens'%}" class="btn btn-success">Lista de Mensagens</a>
            </td>
        </tr>
    </tbody>
</table>
{% endif %}{% endif %}
{% endblock Body %}

core/templates/core/home.html
{% extends "index.html" %} 
{% load widget_tweaks %}
{% block Body %}
<!-- Carrossel -->
<div id="myCarousel" class="carousel slide" data-ride="carousel" style="position: relative; top:15px;">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
            <div class="container">
                <div class="carousel-caption text-left">
                    <h1>Example headline.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at
                        eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Another example headline.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at
                        eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
            <div class="container">
                <div class="carousel-caption text-right">
                    <h1>One more for good measure.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at
                        eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<!-- Fim Carrosel -->

<!-- Sobre -->
<div class="container marketing">
    <hr class="featurette-divider" id="Sobre">

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod
                semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus
                commodo.
            </p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod
                semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus
                commodo.
            </p>
        </div>
        <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
            <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod
                semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus
                commodo.
            </p>
        </div>
        <div class="col-md-5">
            <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
    </div>

    <hr class="featurette-divider">
</div>
<!-- Fim Sobre -->

{% endblock Body %}