Accounts/urls.py
from django.conf.urls import url
from . import views

app_name = "accounts"

urlpatterns = [
    url('^login-usuario/$', views.user_login, name='user-login'),
    url('^logout-usuario/$', views.user_logout, name='user-logout'),
    url('^novo-usuario/$', views.add_user, name='add-user'),
    url('^alterar-senha/$', views.change_password, name='change-password'),
    url('^update-dados/$', views.update_dados, name='update-dados'),
    url('^lista-usuarios/$', views.lista_usuarios, name = 'lista-usuarios'),
    url('^delete-usuario/(?P<id>[0-9]+)/$', views.delete_usuario, name = 'delete-usuario'),
    url('^update-usuario/(?P<id>[0-9]+)/$', views.update_usuario, name = 'update-usuario'),
]

Agendar_horario/urls.py
from django.conf.urls import url

from . import views
app_name = "agenda"
urlpatterns = [
    url('^lista/$', views.lista_agenda, name = 'lista-horario'),
    url('^novo-horario/$', views.add_horario, name = 'novo-horario'),
    url('^editar-horario/(?P<id>[0-9]+)/$', views.update_horario, name = 'editar-horario'),
    url('^excluir-horario/(?P<id>[0-9]+)/$', views.delete_horario, name = 'excluir-horario'),
]

New_Meire/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views
from Mensagens import views as mensagens_views
from Accounts import urls as accounts_urls
from Mensagens import urls as mensagens_urls
from Servico import urls as servico_urls
from Promocao import urls as promocao_urls
from cabeleireira import urls as cabeleireira_urls
from Agendar_horario import urls as agenda_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'core'),
    path('404', views.error_404, name ='error-404'),
    path('em-andamento', views.em_andamento, name ='em-andamento'),
    path('gerencia', views.gerencia, name='gerencia'),
    path('contato/', mensagens_views.nova_mensagem, name = 'contato'),
    path('accounts/', include(accounts_urls)),
    path('msg/', include(mensagens_urls)),
    path('servico/', include(servico_urls)),
    path('promocoes/', include(promocao_urls)),
    path('cabeleireira/', include(cabeleireira_urls)),
    path('agenda/', include(agenda_urls)),
]

Promocao/urls.py
from django.conf.urls import url

from . import views
app_name = "promoções"
urlpatterns = [
    url('lista/', views.lista_promocoes, name = 'lista-promocoes'),
    url('nova/', views.add_promocao, name = 'nova-promocao'),
    url('editar/(?P<id>[0-9]+)/$', views.update_promocao, name = 'editar-promocao'),
    url('excluir/(?P<id>[0-9]+)/$', views.delete_promocao, name = 'excluir-promocao'),
]

Servico/urls.py
from django.conf.urls import url

from . import views
app_name = "servico"
urlpatterns = [
    url('^all-services/$', views.lista_servico, name = 'lista-servicos'),
    url('^novo-servico/$', views.add_servico, name = 'novo-servico'),
    url('^editar-servico/(?P<id>[0-9]+)/$', views.update_servico, name = 'editar-servico'),
    url('^excluir-servico/(?P<id>[0-9]+)/$', views.delete_servico, name = 'excluir-servico'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'core/home.html') #  Função usada para exibir o home

def error_404(request):
    return render(request, 'core/404.html')

def em_andamento(request):
    return render(request, 'core/em_andamento.html')

def gerencia(request):
    return render (request, 'core/gerencia.html')

core/templates/index.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html lang="pt">

<head>
    <meta charset="utf-8">
    <title>Centro da Beleza</title>

    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Bootstrap CSS do home -->
    <link href="{% static "css/carousel.css" %}" rel="stylesheet">

    <!-- Outros estilos -->
    <link href="{% static "css/estilo-proprio.css" %}" rel="stylesheet">

</head>

<body>

    {% if user.is_authenticated %} {% if user.is_superuser %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="{% url 'core' %}">New Meire</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'promoções:lista-promocoes'%}">Promoções</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'servico:lista-servicos'%}">Serviços</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'agenda:lista-horario' %}">Agendar Horário</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contato'%}">Contato</a>
                </li>
            </ul>
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    {% if user.is_authenticated %}{{user.get_full_name|default:user.username}}{% endif %}
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'gerencia' %}">Gerenciar Pagina</a>
                    <a class="dropdown-item" href="{% url 'accounts:change-password' %}">Trocar Senha</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'accounts:user-logout' %}" class="dropdown-item">Logout</a>
                </div>
            </div>
        </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="{% url 'core' %}">New Meire</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'promoções:lista-promocoes'%}">Promoções</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'servico:lista-servicos'%}">Serviços</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'agenda:lista-horario' %}">Agendar Horário</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contato'%}">Contato</a>
                </li>
            </ul>
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    {% if user.is_authenticated %}{{user.get_full_name|default:user.username}}{% endif %}
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'accounts:update-dados' %}">Atualizar dados</a>
                    <a class="dropdown-item" href="{% url 'accounts:change-password' %}">Trocar Senha</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'accounts:user-logout' %}" class="dropdown-item">Logout</a>
                </div>
            </div>
        </div>
    </nav>
    {% endif %} {% else %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="{% url 'core' %}">New Meire</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'promoções:lista-promocoes'%}">Promoções</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'servico:lista-servicos'%}">Serviços</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'contato'%}">Contato</a>
                </li>
            </ul>

            <a class="btn btn-light" href="{% url 'accounts:user-login' %}">Login</a>

        </div>
    </nav>
    {% endif %}
    <div class="container" style="background-color: #f5f5f5; position: relative; bottom:25px;">
        {% block Body %}
        <!-- Bloco utilizado para prover o conteudo para pagina, de outros componetes do django -->

        {% endblock Body %}

    </div>
    <footer class="container">
        <p>&copy; 2018 New Meire Centro de beleza</p>
    </footer>
    <!-- Bootstrap core JavaScript
            ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/holder.min.js" %}"></script>
</body>

</html>