New_Meire/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views
from Mensagens import views as mensagens_views
from Accounts import urls as accounts_urls
from Mensagens import urls as mensagens_urls
from Servico import urls as servico_urls
from Promocao import urls as promocao_urls
from cabeleireira import urls as cabeleireira_urls
from Agendar_horario import urls as agenda_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'core'),
    path('404', views.error_404, name ='error-404'),
    path('em-andamento', views.em_andamento, name ='em-andamento'),
    path('gerencia', views.gerencia, name='gerencia'),
    path('contato/', mensagens_views.nova_mensagem, name = 'contato'),
    path('accounts/', include(accounts_urls)),
    path('msg/', include(mensagens_urls)),
    path('servico/', include(servico_urls)),
    path('promocoes/', include(promocao_urls)),
    path('cabeleireira/', include(cabeleireira_urls)),
    path('agenda/', include(agenda_urls)),
]

Servico/urls.py
from django.conf.urls import url

from . import views
app_name = "servico"
urlpatterns = [
    url('^all-services/$', views.lista_servico, name = 'lista-servicos'),
    url('^novo-servico/$', views.add_servico, name = 'novo-servico'),
    url('^editar-servico/(?P<id>[0-9]+)/$', views.update_servico, name = 'editar-servico'),
    url('^excluir-servico/(?P<id>[0-9]+)/$', views.delete_servico, name = 'excluir-servico'),
]

cabeleireira/urls.py
from django.conf.urls import url

from . import views
app_name = "cabeleireira"
urlpatterns = [
    url('^lista-cabeleireira/$', views.lista_cabeleireira, name = 'lista-cabeleireira'),
    url('^nova-cabeleireira/$', views.add_cabeleireira, name = 'nova-cabeleireira'),
    url('^editar-cabeleireira/(?P<id>[0-9]+)/$', views.update_cabeleireira, name = 'editar-cabeleireira'),
    url('^excluir-cabeleireira/(?P<id>[0-9]+)/$', views.delete_cabeleireira, name = 'excluir-cabeleireira'),
    url('^novo-servico-cabeleireira/$', views.add_servicos_cabeleireira, name = 'novo-servico-cabeleireira'),
    url('^lista-servico-cabeleireira/(?P<id>[0-9]+)/$', views.lista_servicos_cabeleireira, name = 'lista-servico-cabeleireira'),
    url('^editar-servico-cabeleireira/(?P<id>[0-9]+)/$', views.update_servico_cabeleireira, name = 'editar-servico-cabeleireira'),
    url('^excluir-servico-cabeleireira/(?P<id>[0-9]+)/$', views.delete_servico_cabeleireira, name = 'excluir-servico-cabeleireira'),
]

cabeleireira/models.py
from django.db import models
from Servico.models import Servico

# Create your models here.

class Cabeleireira(models.Model):
    nome = models.CharField(max_length=200, verbose_name= 'Nome', blank=False)
    numero = models.CharField(max_length=11, verbose_name='Numero de telefone', blank=False)
    trabalhos_realizados = models.IntegerField(verbose_name='Trabalhos realizadaos', default=0, blank=True)

    def __str__(self):
        return self.nome

class Cabeleireira_Servico(models.Model):
    cabeleireira = models.ForeignKey (Cabeleireira, on_delete=models.CASCADE)
    servico = models.OneToOneField (Servico, on_delete=models.CASCADE)

    def __str__(self):
        return self.cabeleireira.nome + ' - ' + self.servico.servico

cabeleireira/forms.py
from django import forms
from .models import Cabeleireira, Cabeleireira_Servico

class CabeleireiraForm(forms.ModelForm):
    class Meta:
        model = Cabeleireira
        fields = '__all__'

class Cabeleireira_ServicoForm(forms.ModelForm):
    class Meta:
        model = Cabeleireira_Servico
        fields = '__all__'

cabeleireira/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Cabeleireira, Cabeleireira_Servico
from .forms import CabeleireiraForm, Cabeleireira_ServicoForm

##########################################
#Cabeleireira#
##########################################

@login_required
def lista_cabeleireira(request):
    if request.user.is_superuser:
        cabeleireiras = Cabeleireira.objects.all()
        return render(request, 'lista_cabeleireira.html', {'cabeleireiras': cabeleireiras})
    else:
        return redirect('error-404')

@login_required
def add_cabeleireira(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = CabeleireiraForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Cabeleireira criada com Sucesso!')
                return redirect('cabeleireira:lista-cabeleireira')
            else:
                messages.error(request, form.errors)
        else:
            form = CabeleireiraForm()
        return render(request, 'add_cabeleireira.html', {'form':form})
    else:
        return redirect('error-404')

@login_required
def update_cabeleireira(request, id):
    if request.user.is_superuser:
        cabeleireira = Cabeleireira.objects.get(id=id)
        if request.method == 'POST':
            form = CabeleireiraForm(data=request.POST, instance=cabeleireira)
            if form.is_valid():
                form.save()
                messages.success(request, 'Cabeleireira editada com Sucesso!')
                return redirect('cabeleireira:lista-cabeleireira')
            else:
                messages.error(request, form.errors)
        else:
            form = CabeleireiraForm(instance=cabeleireira)
        return render(request, 'add_cabeleireira.html', {'form':form})
    else:
        return redirect('error-404')

@login_required
def delete_cabeleireira(resquest, id):
    if resquest.user.is_superuser:
        cabeleireira = Cabeleireira.objects.get(id=id)
        cabeleireira.delete()
        return redirect('cabeleireira:lista-cabeleireira')
    else:
        return redirect('error-404')

##########################################
#Fim Cabeleireira#
##########################################

##########################################
#Cabeleireira_Serviço#
##########################################
@login_required
def lista_servicos_cabeleireira(request, id):
    if request.user.is_superuser:
        cabeleireira = Cabeleireira.objects.get(id=id)
        nome = cabeleireira.nome
        cabeleireira_servico = Cabeleireira_Servico.objects.filter(cabeleireira=cabeleireira)
        return render(request, 'lista_servicos_cabeleireira.html', {'cabeleireira_servico': cabeleireira_servico, 'nome': nome})
    else:
        return redirect('error-404')

@login_required
def add_servicos_cabeleireira(request):
    if request.user.is_superuser:
        if request.method == 'POST':
            form = Cabeleireira_ServicoForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Serviço atribuido para cabeleireira com Sucesso!')
                return redirect('cabeleireira:lista-cabeleireira')
            else:
                messages.error(request, form.errors)
        else:
            form = Cabeleireira_ServicoForm()
        return render(request, 'add_servico_cabeleireira.html', {'form':form})
    else:
        return redirect('error-404')

@login_required
def update_servico_cabeleireira(request, id):
    if request.user.is_superuser:
        cabeleireira_servico = Cabeleireira_Servico.objects.get(id=id)
        if request.method == 'POST':
            form = Cabeleireira_ServicoForm(data=request.POST, instance=cabeleireira_servico)
            if form.is_valid():
                form.save()
                messages.success(request, 'Serviço da cabeleireira editado com Sucesso!')
                return redirect('cabeleireira:lista-cabeleireira')
            else:
                messages.error(request, form.errors)
        else:
            form = Cabeleireira_ServicoForm(instance=cabeleireira_servico)
        return render(request, 'add_servico_cabeleireira.html', {'form':form})
    else:
        return redirect('error-404')

@login_required
def delete_servico_cabeleireira(resquest, id):
    if resquest.user.is_superuser:
        cabeleireira_servico = Cabeleireira_Servico.objects.get(id=id)
        id_cab = cabeleireira_servico.cabeleireira.id
        cabeleireira_servico.delete()
        return redirect('cabeleireira:lista-servico-cabeleireira', id_cab)
    else:
        return redirect('error-404')

##########################################
#Fim Cabeleireira_Serviço#
##########################################

cabeleireira/templates/add_cabeleireira.html
{% extends "index.html" %}
{% load widget_tweaks %}
{% block Body %}
{% if user.is_authenticated %}
{% if user.is_superuser %}
<form class="form-signin" method="post">
    {% csrf_token %}

    {% if messages %}
    <div class="alert alert-info" role="alert">
        {% for m in messages %} {{ m }} {% endfor %}
    </div>
    {% endif %}

    <div class="form-group">
        <label for="{{form.nome.id_for_label}}">Nome:</label>
        {{form.nome|add_class:'form-control'|attr:"placeholder:Nome"}}
    </div>
    <div class="form-group">
        <label for="{{form.numero.id_for_label}}">Numero de Telefone:</label>
        {{form.numero|add_class:'form-control'|attr:"placeholder:Numero de Telefone"}}
    </div>
    <div class="form-group">
        <label for="{{form.trabalhos_realizados.id_for_label}}">Nº de Trabalhos Realizados:</label>
        {{form.trabalhos_realizados|add_class:'form-control'|attr:"placeholder:Nº de Trabalhos Realizados"}}
    </div>
    
    <button class="btn btn-lg btn-primary btn-block" type="submit">Salvar</button>
    <a href="{% url 'cabeleireira:lista-cabeleireira' %}" class="btn btn-lg btn-info btn-block">Voltar</a>
</form>

{% endif %}
{% else %}
<h3 class="h3 mb-3 font-weight-normal">Você precisa estar logado!.</h3>
{% endif %}
{% endblock Body %}

cabeleireira/templates/add_servico_cabeleireira.html
{% extends "index.html" %}
{% load widget_tweaks %}
{% block Body %}
{% if user.is_authenticated %}
{% if user.is_superuser %}
<form class="form-signin" method="post">
    {% csrf_token %}

    {% if messages %}
    <div class="alert alert-info" role="alert">
        {% for m in messages %} {{ m }} {% endfor %}
    </div>
    {% endif %}

    <div class="form-group">
        <label for="{{form.cabeleireira.id_for_label}}">Cabeleireira:</label>
        {{form.cabeleireira|add_class:'form-control'|attr:"placeholder:Cabeleireira"}}
    </div>
    <div class="form-group">
        <label for="{{form.servico.id_for_label}}">ServiÇo:</label>
        {{form.servico|add_class:'form-control'|attr:"placeholder:ServiÇo"}}
    </div>
    
    <button class="btn btn-lg btn-primary btn-block" type="submit">Salvar</button>
    <a href="{% url 'cabeleireira:lista-cabeleireira' %}" class="btn btn-lg btn-info btn-block">Voltar</a>
</form>

{% endif %}
{% else %}
<h3 class="h3 mb-3 font-weight-normal">Você precisa estar logado!.</h3>
{% endif %}
{% endblock Body %}

cabeleireira/templates/lista_cabeleireira.html
{% extends "index.html" %}
{% block Body %}
{% if user.is_authenticated %} 
{% if user.is_superuser %}
<div class="row">
        <h1>Lista de Cabeleireiras</h1>
        {% if messages %}
            {% for m in messages %}
                <div class="alert alert-info" role="alert">
                    {{m}}
                </div>
            {% endfor %}
        {% endif %}
        {% if cabeleireiras %}

            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Telefone</th>
                        <th>Trabalhos Realizados</th>
                        <th colspan="2">Ações</th>
                    </tr>
                </thead>
                <tbody>
                    {% for c in cabeleireiras %}
                        <tr>
                            <td>{{c.id}}</td>
                            <td>{{c.nome}}</td>
                            <td>{{c.numero}}</td>
                            <td>{{c.trabalhos_realizados}}</td>
                            <td><a href="{% url 'cabeleireira:editar-cabeleireira' c.id %}" class="btn btn-success">Editar</a></td>
                            <td><a href="{% url 'cabeleireira:lista-servico-cabeleireira' c.id %}" class="btn btn-primary">Lista de Serviços</a></td>
                            <td><a href="{% url 'cabeleireira:excluir-cabeleireira' c.id %}" class="btn btn-danger">Excluir</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-info">
                <p>Ainda não recebeu nenhuma mensagem!</p>
            </div>
        {% endif %}
        
            <a href="{% url 'cabeleireira:nova-cabeleireira' %}" class="btn btn-lg btn-info btn-block">Adicionar Cabeleireira</a>
        </div>
{% endif %}{% endif %}
{% endblock Body %}

cabeleireira/templates/lista_servicos_cabeleireira.html
{% extends "index.html" %}
{% block Body %}
{% if user.is_authenticated %}
{% if user.is_superuser %}
<div class="row">
    <h1>Lista de Serviços que podem ser realizados por: {{nome}}</h1>
    {% if messages %}
    {% for m in messages %}
    <div class="alert alert-danger" role="alert">
        {{m}}
    </div>
    {% endfor %}
    {% endif %}
    {% if cabeleireira_servico %}

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Nome</th>
                <th>Serviço</th>
                <th colspan="2">Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for sc in cabeleireira_servico %}
            <tr>
                <td>{{sc.id}}</td>
                <td>{{sc.cabeleireira.nome}}</td>
                <td>{{sc.servico.servico}}</td>

                <td><a href="{% url 'cabeleireira:editar-servico-cabeleireira' sc.id %}" class="btn btn-success">Editar</a></td>
                <td><a href="{% url 'cabeleireira:excluir-servico-cabeleireira' sc.id %}" class="btn btn-danger">Excluir</a></td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div class="alert alert-info">
        <p>Ainda não realiza nenhum Serviço!</p>
        <a href="{% url 'cabeleireira:novo-servico-cabeleireira'%}" class="btn btn-info">Adicionar serviço a um
            profissonal</a>
    </div>


{% endif %}

    
    <a href="{% url 'cabeleireira:novo-servico-cabeleireira'%}" class="btn btn-lg btn-secondary btn-block">Adicionar serviço a um
        profissonal</a>
    <a href="{% url 'cabeleireira:lista-cabeleireira' %}" class="btn btn-lg btn-info btn-block">Voltar</a>

</div>
{% endif %}{% endif %}
{% endblock Body %}